name: "RDT"
version: ${version}
main: com.raindropcentral.rdt.RDTFree
api-version: '1.19'
description: ${description}
author: RaindropCentral
website: https://raindropcentral.com
softdepend:
  - Vault
  - TheNewEconomy
  - RCore
