name: RCorePremium
main: com.raindropcentral.rcore.RCorePremium
version: 2.0.0
api-version: "1.16"
description: RCore
authors: [ ItsRainingHP, JExcellence ]
website: https://www.raindropcentral.com
softdepend:
  - JECurrency
  - LuckPerms
  - Aura
  - ChestSort
  - CMI
  - DiscordSRV
  - EcoJobs
  - Essentials
  - EssentialsChat
  - EssentialsDiscord
  - EssentialsSpawn
  - HuskTowns
  - Jobs
  - mcMMO
  - Towny
  - TownyChat