package de.jexcellence.oneblock.manager.storage;

import de.jexcellence.oneblock.database.entity.storage.StorageCategory;
import de.jexcellence.oneblock.database.entity.storage.StoredItem;
import org.bukkit.Material;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.Collectors;

/**
 * Category Manager for Enhanced Storage System
 * 
 * Manages smart categorization, custom categories, and category-based operations
 * for the storage system with advanced filtering and organization capabilities.
 * 
 * @author JExcellence
 * @version 2.0.0
 * @since 2.0.0
 */
public class CategoryManager {
    
    private final Map<Long, Map<StorageCategory, CategoryStats>> islandCategoryStats = new ConcurrentHashMap<>();
    private final Map<Long, Set<StorageCategory>> customCategories = new ConcurrentHashMap<>();
    private final Map<Material, StorageCategory> materialCategoryCache = new ConcurrentHashMap<>();
    
    /**
     * Category statistics for tracking usage and optimization
     */
    public static class CategoryStats {
        private long totalItems;
        private int uniqueTypes;
        private long lastAccessed;
        private double accessFrequency;
        private boolean isAutoGenerated;
        
        public CategoryStats() {
            this.lastAccessed = System.currentTimeMillis();
            this.isAutoGenerated = true;
        }
        
        public long getTotalItems() { return totalItems; }
        public void setTotalItems(long totalItems) { this.totalItems = totalItems; }
        
        public int getUniqueTypes() { return uniqueTypes; }
        public void setUniqueTypes(int uniqueTypes) { this.uniqueTypes = uniqueTypes; }
        
        public long getLastAccessed() { return lastAccessed; }
        public void setLastAccessed(long lastAccessed) { this.lastAccessed = lastAccessed; }
        
        public double getAccessFrequency() { return accessFrequency; }
        public void setAccessFrequency(double accessFrequency) { this.accessFrequency = accessFrequency; }
        
        public boolean isAutoGenerated() { return isAutoGenerated; }
        public void setAutoGenerated(boolean autoGenerated) { this.isAutoGenerated = autoGenerated; }
        
        public void recordAccess() {
            long currentTime = System.currentTimeMillis();
            long timeSinceLastAccess = currentTime - lastAccessed;
            
            // Update access frequency using exponential moving average
            if (timeSinceLastAccess > 0) {
                double newFrequency = 1.0 / (timeSinceLastAccess / 1000.0); // Access per second
                accessFrequency = (accessFrequency * 0.9) + (newFrequency * 0.1);
            }
            
            lastAccessed = currentTime;
        }
    }
    
    /**
     * Category filter for advanced filtering operations
     */
    public static class CategoryFilter {
        private Set<StorageCategory> includedCategories = new HashSet<>();
        private Set<StorageCategory> excludedCategories = new HashSet<>();
        private boolean showEmpty = false;
        private boolean showAutoGenerated = true;
        private boolean showCustom = true;
        private SortOrder sortOrder = SortOrder.ALPHABETICAL;
        
        public enum SortOrder {
            ALPHABETICAL, ITEM_COUNT, LAST_ACCESSED, ACCESS_FREQUENCY, CATEGORY_TYPE
        }
        
        public Set<StorageCategory> getIncludedCategories() { return includedCategories; }
        public void setIncludedCategories(Set<StorageCategory> includedCategories) { this.includedCategories = includedCategories; }
        
        public Set<StorageCategory> getExcludedCategories() { return excludedCategories; }
        public void setExcludedCategories(Set<StorageCategory> excludedCategories) { this.excludedCategories = excludedCategories; }
        
        public boolean isShowEmpty() { return showEmpty; }
        public void setShowEmpty(boolean showEmpty) { this.showEmpty = showEmpty; }
        
        public boolean isShowAutoGenerated() { return showAutoGenerated; }
        public void setShowAutoGenerated(boolean showAutoGenerated) { this.showAutoGenerated = showAutoGenerated; }
        
        public boolean isShowCustom() { return showCustom; }
        public void setShowCustom(boolean showCustom) { this.showCustom = showCustom; }
        
        public SortOrder getSortOrder() { return sortOrder; }
        public void setSortOrder(SortOrder sortOrder) { this.sortOrder = sortOrder; }
    }
    
    /**
     * Gets the category for a material with caching
     * 
     * @param material the material to categorize
     * @return the storage category
     */
    @NotNull
    public StorageCategory getCategoryForMaterial(@NotNull Material material) {
        return materialCategoryCache.computeIfAbsent(material, StorageCategory::categorize);
    }
    
    /**
     * Updates category statistics for an island
     * 
     * @param islandId the island ID
     * @param storedItems the stored items to analyze
     */
    public void updateCategoryStats(@NotNull Long islandId, @NotNull Map<Material, Long> storedItems) {
        Map<StorageCategory, CategoryStats> stats = islandCategoryStats.computeIfAbsent(islandId, k -> new ConcurrentHashMap<>());
        
        // Clear existing stats
        stats.clear();
        
        // Group items by category
        Map<StorageCategory, List<Map.Entry<Material, Long>>> categoryGroups = storedItems.entrySet().stream()
            .collect(Collectors.groupingBy(entry -> getCategoryForMaterial(entry.getKey())));
        
        // Calculate stats for each category
        for (Map.Entry<StorageCategory, List<Map.Entry<Material, Long>>> categoryGroup : categoryGroups.entrySet()) {
            StorageCategory category = categoryGroup.getKey();
            List<Map.Entry<Material, Long>> items = categoryGroup.getValue();
            
            CategoryStats categoryStats = stats.computeIfAbsent(category, k -> new CategoryStats());
            
            long totalItems = items.stream().mapToLong(Map.Entry::getValue).sum();
            int uniqueTypes = items.size();
            
            categoryStats.setTotalItems(totalItems);
            categoryStats.setUniqueTypes(uniqueTypes);
        }
    }
    
    /**
     * Gets category statistics for an island
     * 
     * @param islandId the island ID
     * @return map of category statistics
     */
    @NotNull
    public Map<StorageCategory, CategoryStats> getCategoryStats(@NotNull Long islandId) {
        return islandCategoryStats.getOrDefault(islandId, new HashMap<>());
    }
    
    /**
     * Gets filtered and sorted categories for an island
     * 
     * @param islandId the island ID
     * @param filter the category filter
     * @return filtered and sorted list of categories
     */
    @NotNull
    public List<StorageCategory> getFilteredCategories(@NotNull Long islandId, @NotNull CategoryFilter filter) {
        Map<StorageCategory, CategoryStats> stats = getCategoryStats(islandId);
        
        return Arrays.stream(StorageCategory.values())
            .filter(category -> shouldIncludeCategory(category, stats.get(category), filter))
            .sorted(createCategoryComparator(stats, filter.getSortOrder()))
            .collect(Collectors.toList());
    }
    
    /**
     * Gets the most accessed categories for an island
     * 
     * @param islandId the island ID
     * @param limit the maximum number of categories to return
     * @return list of most accessed categories
     */
    @NotNull
    public List<StorageCategory> getMostAccessedCategories(@NotNull Long islandId, int limit) {
        Map<StorageCategory, CategoryStats> stats = getCategoryStats(islandId);
        
        return stats.entrySet().stream()
            .sorted((a, b) -> Double.compare(b.getValue().getAccessFrequency(), a.getValue().getAccessFrequency()))
            .limit(limit)
            .map(Map.Entry::getKey)
            .collect(Collectors.toList());
    }
    
    /**
     * Gets categories with the most items for an island
     * 
     * @param islandId the island ID
     * @param limit the maximum number of categories to return
     * @return list of categories with most items
     */
    @NotNull
    public List<StorageCategory> getCategoriesWithMostItems(@NotNull Long islandId, int limit) {
        Map<StorageCategory, CategoryStats> stats = getCategoryStats(islandId);
        
        return stats.entrySet().stream()
            .sorted((a, b) -> Long.compare(b.getValue().getTotalItems(), a.getValue().getTotalItems()))
            .limit(limit)
            .map(Map.Entry::getKey)
            .collect(Collectors.toList());
    }
    
    /**
     * Records access to a category for analytics
     * 
     * @param islandId the island ID
     * @param category the accessed category
     */
    public void recordCategoryAccess(@NotNull Long islandId, @NotNull StorageCategory category) {
        Map<StorageCategory, CategoryStats> stats = islandCategoryStats.computeIfAbsent(islandId, k -> new ConcurrentHashMap<>());
        CategoryStats categoryStats = stats.computeIfAbsent(category, k -> new CategoryStats());
        categoryStats.recordAccess();
    }
    
    /**
     * Gets category efficiency metrics
     * 
     * @param islandId the island ID
     * @return map of category efficiency scores
     */
    @NotNull
    public Map<StorageCategory, Double> getCategoryEfficiency(@NotNull Long islandId) {
        Map<StorageCategory, CategoryStats> stats = getCategoryStats(islandId);
        Map<StorageCategory, Double> efficiency = new HashMap<>();
        
        for (Map.Entry<StorageCategory, CategoryStats> entry : stats.entrySet()) {
            StorageCategory category = entry.getKey();
            CategoryStats categoryStats = entry.getValue();
            
            // Calculate efficiency based on items per type ratio and access frequency
            double itemsPerType = categoryStats.getUniqueTypes() > 0 ? 
                (double) categoryStats.getTotalItems() / categoryStats.getUniqueTypes() : 0;
            
            double efficiencyScore = (itemsPerType * 0.7) + (categoryStats.getAccessFrequency() * 0.3);
            efficiency.put(category, efficiencyScore);
        }
        
        return efficiency;
    }
    
    /**
     * Suggests category optimizations for an island
     * 
     * @param islandId the island ID
     * @return list of optimization suggestions
     */
    @NotNull
    public List<CategoryOptimization> suggestOptimizations(@NotNull Long islandId) {
        List<CategoryOptimization> suggestions = new ArrayList<>();
        Map<StorageCategory, CategoryStats> stats = getCategoryStats(islandId);
        Map<StorageCategory, Double> efficiency = getCategoryEfficiency(islandId);
        
        for (Map.Entry<StorageCategory, CategoryStats> entry : stats.entrySet()) {
            StorageCategory category = entry.getKey();
            CategoryStats categoryStats = entry.getValue();
            double efficiencyScore = efficiency.getOrDefault(category, 0.0);
            
            // Suggest splitting large categories
            if (categoryStats.getUniqueTypes() > 50 && efficiencyScore < 10.0) {
                suggestions.add(new CategoryOptimization(
                    category,
                    CategoryOptimization.Type.SPLIT_CATEGORY,
                    "Category has too many item types (" + categoryStats.getUniqueTypes() + "). Consider creating subcategories.",
                    CategoryOptimization.Priority.MEDIUM
                ));
            }
            
            // Suggest merging rarely accessed categories
            if (categoryStats.getAccessFrequency() < 0.1 && categoryStats.getTotalItems() < 100) {
                suggestions.add(new CategoryOptimization(
                    category,
                    CategoryOptimization.Type.MERGE_CATEGORY,
                    "Category is rarely accessed and has few items. Consider merging with similar category.",
                    CategoryOptimization.Priority.LOW
                ));
            }
            
            // Suggest creating quick access for frequently used categories
            if (categoryStats.getAccessFrequency() > 5.0) {
                suggestions.add(new CategoryOptimization(
                    category,
                    CategoryOptimization.Type.CREATE_QUICK_ACCESS,
                    "Category is frequently accessed. Consider adding to quick access menu.",
                    CategoryOptimization.Priority.HIGH
                ));
            }
        }
        
        return suggestions;
    }
    
    /**
     * Clears category cache and statistics
     */
    public void clearCache() {
        materialCategoryCache.clear();
        islandCategoryStats.clear();
        customCategories.clear();
    }
    
    /**
     * Clears cache for a specific island
     * 
     * @param islandId the island ID
     */
    public void clearIslandCache(@NotNull Long islandId) {
        islandCategoryStats.remove(islandId);
        customCategories.remove(islandId);
    }
    
    /**
     * Checks if a category should be included based on filter criteria
     */
    private boolean shouldIncludeCategory(@NotNull StorageCategory category, @Nullable CategoryStats stats, @NotNull CategoryFilter filter) {
        // Check inclusion/exclusion lists
        if (!filter.getIncludedCategories().isEmpty() && !filter.getIncludedCategories().contains(category)) {
            return false;
        }
        
        if (filter.getExcludedCategories().contains(category)) {
            return false;
        }
        
        // Check if category has items (unless showing empty is enabled)
        if (!filter.isShowEmpty() && (stats == null || stats.getTotalItems() == 0)) {
            return false;
        }
        
        // Check auto-generated vs custom filter
        if (stats != null) {
            if (!filter.isShowAutoGenerated() && stats.isAutoGenerated()) {
                return false;
            }
            
            if (!filter.isShowCustom() && !stats.isAutoGenerated()) {
                return false;
            }
        }
        
        return true;
    }
    
    /**
     * Creates a comparator for sorting categories based on the specified order
     */
    @NotNull
    private Comparator<StorageCategory> createCategoryComparator(@NotNull Map<StorageCategory, CategoryStats> stats, 
                                                                @NotNull CategoryFilter.SortOrder sortOrder) {
        return switch (sortOrder) {
            case ALPHABETICAL -> Comparator.comparing(StorageCategory::getDisplayName);
            case ITEM_COUNT -> (a, b) -> {
                CategoryStats statsA = stats.get(a);
                CategoryStats statsB = stats.get(b);
                long itemsA = statsA != null ? statsA.getTotalItems() : 0;
                long itemsB = statsB != null ? statsB.getTotalItems() : 0;
                return Long.compare(itemsB, itemsA); // Descending order
            };
            case LAST_ACCESSED -> (a, b) -> {
                CategoryStats statsA = stats.get(a);
                CategoryStats statsB = stats.get(b);
                long accessA = statsA != null ? statsA.getLastAccessed() : 0;
                long accessB = statsB != null ? statsB.getLastAccessed() : 0;
                return Long.compare(accessB, accessA); // Most recent first
            };
            case ACCESS_FREQUENCY -> (a, b) -> {
                CategoryStats statsA = stats.get(a);
                CategoryStats statsB = stats.get(b);
                double freqA = statsA != null ? statsA.getAccessFrequency() : 0;
                double freqB = statsB != null ? statsB.getAccessFrequency() : 0;
                return Double.compare(freqB, freqA); // Descending order
            };
            case CATEGORY_TYPE -> (a, b) -> {
                CategoryStats statsA = stats.get(a);
                CategoryStats statsB = stats.get(b);
                boolean autoA = statsA != null ? statsA.isAutoGenerated() : true;
                boolean autoB = statsB != null ? statsB.isAutoGenerated() : true;
                
                if (autoA != autoB) {
                    return autoA ? 1 : -1; // Custom categories first
                }
                
                return a.getDisplayName().compareTo(b.getDisplayName());
            };
        };
    }
    
    /**
     * Category optimization suggestion
     */
    public static class CategoryOptimization {
        private final StorageCategory category;
        private final Type type;
        private final String description;
        private final Priority priority;
        
        public enum Type {
            SPLIT_CATEGORY, MERGE_CATEGORY, CREATE_QUICK_ACCESS, REORGANIZE_ITEMS
        }
        
        public enum Priority {
            LOW, MEDIUM, HIGH, CRITICAL
        }
        
        public CategoryOptimization(@NotNull StorageCategory category, @NotNull Type type, 
                                  @NotNull String description, @NotNull Priority priority) {
            this.category = category;
            this.type = type;
            this.description = description;
            this.priority = priority;
        }
        
        public StorageCategory getCategory() { return category; }
        public Type getType() { return type; }
        public String getDescription() { return description; }
        public Priority getPriority() { return priority; }
    }
}