name: "RDA"
version: ${version}
main: com.raindropcentral.rda.RDAFree
api-version: '1.19'
description: ${description}
author: RaindropCentral
website: https://raindropcentral.com
softdepend:
  - RCore
