name: ${name}
version: ${version}
main: de.jexcellence.workbench.JExWorkbench
description: ${description}
api-version: ${apiVersion}
author: JExcellence
website: https://www.jexcellence.de

dependencies:
  server:
    Vault:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
