name: "RDQ"
version: ${version}
main: com.raindropcentral.rdq.RDQPremium
api-version: ${apiVersion}
description: ${description}
author: RaindropCentral
website: https://raindropcentral.com
softdepend:
  - Vault
  - LuckPerms
  - PlaceholderAPI