name: "JExMultiverse"
version: ${version}
main: de.jexcellence.multiverse.JExMultiversePremium
api-version: ${apiVersion}
description: ${description}
author: JExcellence
website: https://jexcellence.de
loadbefore:
  - JExOneblock