/**
 * Convention plugin for generating dependencies.yml files from centralized RuntimeDependencies.
 * 
 * Usage in build.gradle.kts:
 * ```
 * plugins {
 *     id("raindrop.dependencies-yml")
 * }
 * 
 * // Configure which dependency set to use
 * dependenciesYml {
 *     useRCoreDependencies()
 *     // Or for plugins with Paper/Spigot variants:
 *     usePaperDependencies()
 *     generatePaperVariant.set(true)
 *     generateSpigotVariant.set(true)
 * }
 * ```
 */

import RuntimeDependencies.DependencyGroup

// Extension for configuration
abstract class DependenciesYmlExtension {
    // Store as serializable Map<String, List<String>> for Gradle caching
    abstract val dependencyGroups: MapProperty<String, List<String>>
    abstract val paperDependencyGroups: MapProperty<String, List<String>>
    abstract val spigotDependencyGroups: MapProperty<String, List<String>>
    abstract val generatePaperVariant: Property<Boolean>
    abstract val generateSpigotVariant: Property<Boolean>
    abstract val outputDir: Property<String>
    
    init {
        dependencyGroups.convention(emptyMap())
        paperDependencyGroups.convention(emptyMap())
        spigotDependencyGroups.convention(emptyMap())
        generatePaperVariant.convention(false)
        generateSpigotVariant.convention(false)
        outputDir.convention("src/main/resources/dependency")
    }
    
    /** Convert DependencyGroup list to serializable map */
    private fun List<DependencyGroup>.toSerializable(): Map<String, List<String>> =
        associate { it.name to it.dependencies }
    
    /** Use RCore's full dependency set */
    fun useRCoreDependencies() {
        dependencyGroups.set(RuntimeDependencies.rcoreFull.toSerializable())
    }
    
    /** Use Paper plugin dependencies with Paper/Spigot variants */
    fun usePaperDependencies() {
        dependencyGroups.set(RuntimeDependencies.pluginFullPaper.toSerializable())
        paperDependencyGroups.set(RuntimeDependencies.pluginFullPaper.toSerializable())
        spigotDependencyGroups.set(RuntimeDependencies.pluginFullSpigot.toSerializable())
    }
    
    /** Use Spigot-only dependencies */
    fun useSpigotDependencies() {
        dependencyGroups.set(RuntimeDependencies.pluginFullSpigot.toSerializable())
    }
    
    /** Use JExDependency's full dependency set */
    fun useJExDependencyDependencies() {
        dependencyGroups.set(RuntimeDependencies.jexdependencyFull.toSerializable())
    }
}

// Task to generate dependencies.yml
abstract class GenerateDependenciesYmlTask : DefaultTask() {
    
    @get:Input
    abstract val dependencyGroups: MapProperty<String, List<String>>
    
    @get:Input
    abstract val outputPath: Property<String>
    
    @get:Input
    abstract val variant: Property<String>
    
    @get:OutputFile
    val outputFile: File
        get() = project.file(outputPath.get())
    
    init {
        variant.convention("default")
    }
    
    @TaskAction
    fun generate() {
        val groups = dependencyGroups.get()
        val output = outputFile
        val variantName = variant.get()
        
        output.parentFile.mkdirs()
        
        val content = buildString {
            appendLine("# =============================================================================")
            appendLine("# Runtime Dependencies Configuration")
            appendLine("# =============================================================================")
            appendLine("# Auto-generated by Gradle - DO NOT EDIT MANUALLY")
            appendLine("# Edit RuntimeDependencies.kt in buildSrc instead")
            if (variantName != "default") {
                appendLine("# Variant: $variantName")
            }
            appendLine("# =============================================================================")
            appendLine()
            appendLine("dependencies:")
            
            groups.forEach { (groupName, deps) ->
                appendLine()
                appendLine("  # $groupName")
                deps.forEach { dep ->
                    appendLine("  - \"$dep\"")
                }
            }
        }
        
        output.writeText(content)
        logger.lifecycle("Generated ${output.relativeTo(project.rootDir)}")
    }
}

// Create extension
val extension = extensions.create<DependenciesYmlExtension>("dependenciesYml")

// Register main task
val generateMain = tasks.register<GenerateDependenciesYmlTask>("generateDependenciesYml") {
    group = "build"
    description = "Generates dependencies.yml from RuntimeDependencies"
    dependencyGroups.set(extension.dependencyGroups)
    outputPath.set(extension.outputDir.map { "$it/dependencies.yml" })
    variant.set("default")
}

// Register Paper variant task
val generatePaper = tasks.register<GenerateDependenciesYmlTask>("generatePaperDependenciesYml") {
    group = "build"
    description = "Generates Paper-specific dependencies.yml"
    dependencyGroups.set(provider { 
        extension.paperDependencyGroups.get().ifEmpty { extension.dependencyGroups.get() }
    })
    outputPath.set(extension.outputDir.map { "$it/paper/dependencies.yml" })
    variant.set("Paper")
    onlyIf { extension.generatePaperVariant.get() }
}

// Register Spigot variant task
val generateSpigot = tasks.register<GenerateDependenciesYmlTask>("generateSpigotDependenciesYml") {
    group = "build"
    description = "Generates Spigot-specific dependencies.yml"
    dependencyGroups.set(provider {
        extension.spigotDependencyGroups.get().ifEmpty { extension.dependencyGroups.get() }
    })
    outputPath.set(extension.outputDir.map { "$it/spigot/dependencies.yml" })
    variant.set("Spigot")
    onlyIf { extension.generateSpigotVariant.get() }
}

// Register combined task
tasks.register("generateAllDependenciesYml") {
    group = "build"
    description = "Generates all dependencies.yml variants"
    dependsOn(generateMain, generatePaper, generateSpigot)
}

// Hook into processResources and sourcesJar - use afterEvaluate to ensure extension is configured
afterEvaluate {
    tasks.matching { it.name == "processResources" }.configureEach {
        dependsOn(generateMain)
        if (extension.generatePaperVariant.get()) dependsOn(generatePaper)
        if (extension.generateSpigotVariant.get()) dependsOn(generateSpigot)
    }
    
    // Also hook into sourcesJar to prevent implicit dependency issues
    tasks.matching { it.name == "sourcesJar" }.configureEach {
        dependsOn(generateMain)
        if (extension.generatePaperVariant.get()) dependsOn(generatePaper)
        if (extension.generateSpigotVariant.get()) dependsOn(generateSpigot)
    }
}
