name: ${name}
main: com.raindropcentral.core.RCore
version: ${version}
api-version: "${apiVersion}"
description: RCore
authors: [ ItsRainingHP, JExcellence ]
website: https://www.raindropcentral.com
softdepend:
  - JExEconomy
  - LuckPerms
  - Aura
  - ChestSort
  - CMI
  - DiscordSRV
  - EcoJobs
  - Essentials
  - EssentialsChat
  - EssentialsDiscord
  - EssentialsSpawn
  - HuskTowns
  - Jobs
  - mcMMO
  - Towny
  - TownyChat
