package com.raindropcentral.core.service;

import com.raindropcentral.core.database.entity.player.RPlayer;
import com.raindropcentral.core.database.entity.statistic.*;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Service class for managing player statistics with comprehensive CRUD operations.
 * <p>
 * This utility provides convenience builders and helpers that operate directly on the
 * Hibernate-managed {@link RPlayerStatistic} aggregate. All mutation methods assume they are
 * executed within the same transactional boundary as the owning {@link RPlayerStatistic} entity
 * and therefore return simple success flags or counts rather than triggering persistence
 * operations themselves.
 * </p>
 *
 * @author JExcellence
 * @since 1.0.0
 * @version 1.0.1
 */
@SuppressWarnings("unused")
public final class RPlayerStatisticService {

    /**
     * Creates a non-instantiable utility container for statistic helpers.
     * Utility access is static-only to guarantee stateless behaviour and to avoid leaking entity
     * references that should be handled by the persistence layer.
     */
    private RPlayerStatisticService() {}

    /**
     * Creates a new {@link RPlayerStatistic} wrapper for the supplied player without preloading
     * values.
     *
     * @param player player aggregate that owns the statistics collection; must already be managed
     *               by the surrounding persistence context
     * @return a fresh statistic container bound to the provided player and ready for transactional
     *         persistence
     */
    public static @NotNull RPlayerStatistic createPlayerStatistic(
            final @NotNull RPlayer player
    ) {
        return new RPlayerStatistic(player);
    }

    /**
     * Creates a new {@link RPlayerStatistic} wrapper for the supplied player and seeds it with
     * initial values.
     *
     * <p>The provided statistics map will be iterated deterministically to either insert new
     * values or update existing ones. Each entry is handled via
     * {@link #addOrUpdateStatistic(RPlayerStatistic, String, String, Object)} to guarantee
     * consistency with the replacement semantics used elsewhere in this service.</p>
     *
     * @param player            player aggregate that owns the statistics collection
     * @param initialStatistics key-value pairs keyed by statistic identifier containing initial
     *                          values
     * @param plugin            plugin namespace responsible for the inserted statistics
     * @return a populated statistic container ready for persistence in the active transaction
     */
    public static @NotNull RPlayerStatistic createPlayerStatisticWithData(
            final @NotNull RPlayer player,
            final @NotNull Map<String, Object> initialStatistics,
            final @NotNull String plugin
    ) {
        final RPlayerStatistic playerStatistic = new RPlayerStatistic(player);

        initialStatistics.forEach((identifier, value) -> {
            // Upsert, so initial loaders don't ever violate unique keys if double-called
            addOrUpdateStatistic(playerStatistic, identifier, plugin, value);
        });

        return playerStatistic;
    }

    /**
     * Adds a statistic or updates an existing entry in-place when compatible with the supplied
     * value type.
     *
     * <p>Identifiers are treated as globally unique for each player. The implementation first
     * resolves any existing statistic via {@link #findByIdentifier(RPlayerStatistic, String)} to
     * guarantee Hibernate tracks the mutation on the managed entity. When a type mismatch occurs,
     * the method removes the prior entry and inserts a replacement generated by
     * {@link #createStatisticFromValue(String, String, Object)}.</p>
     *
     * @param playerStatistic statistic container mutated within the caller's transaction
     * @param identifier      unique identifier for the statistic being added or updated
     * @param plugin          plugin namespace associated with the statistic
     * @param value           value written into the statistic, supporting primitive wrappers,
     *                        {@link String}, {@link LocalDateTime}, or other objects convertible to
     *                        string
     * @return {@code true} when the statistic is stored successfully, regardless of whether an
     * existing record was updated or a new entity was added
     */
    public static boolean addOrUpdateStatistic(
            final @NotNull RPlayerStatistic playerStatistic,
            final @NotNull String identifier,
            final @NotNull String plugin,
            final @NotNull Object value
    ) {
        // Try update in-place by identifier to avoid insert+delete ordering issues
        final Optional<RAbstractStatistic> existingOpt = findByIdentifier(playerStatistic, identifier);

        if (existingOpt.isPresent()) {
            final RAbstractStatistic existing = existingOpt.get();
            
            // Try to update the existing statistic in-place
            if (updateExistingStatistic(existing, value)) {
                // Successfully updated in-place, no need to create new entity
                // Note: We keep the original plugin value to avoid unnecessary changes
                return true;
            }
            
            // Type mismatch: we need to replace the statistic with a new type
            // Use addOrReplaceStatistic which properly handles removal and addition
            final RAbstractStatistic newStatistic = createStatisticFromValue(identifier, plugin, value);
            playerStatistic.addOrReplaceStatistic(newStatistic);
            return true;
        }

        // No existing statistic found - create new entity
        final RAbstractStatistic statistic = createStatisticFromValue(identifier, plugin, value);
        playerStatistic.addOrReplaceStatistic(statistic);
        return true;
    }

    /**
     * Inserts or updates multiple statistics sequentially.
     *
     * <p>Each entry is processed via {@link #addOrUpdateStatistic(RPlayerStatistic, String, String,
     * Object)} ensuring identical transactional behaviour to single updates. The helper returns the
     * number of entries that were successfully applied.</p>
     *
     * @param playerStatistic statistic container mutated within the caller's transaction
     * @param statistics      map of identifiers to values to apply
     * @param plugin          plugin namespace applied to every imported statistic
     * @return count of statistics that were stored or updated
     */
    public static int addStatisticsBulk(
            final @NotNull RPlayerStatistic playerStatistic,
            final @NotNull Map<String, Object> statistics,
            final @NotNull String plugin
    ) {
        int successCount = 0;
        for (Map.Entry<String, Object> entry : statistics.entrySet()) {
            if (addOrUpdateStatistic(playerStatistic, entry.getKey(), plugin, entry.getValue())) {
                successCount++;
            }
        }
        return successCount;
    }

    /**
     * Removes a statistic for the supplied identifier and plugin pairing.
     *
     * <p>The removal first attempts the direct API on {@link RPlayerStatistic}. If the plugin key
     * does not match the stored value, a fallback removes by identifier across all known plugins to
     * avoid leaving orphaned statistics.</p>
     *
     * @param playerStatistic statistic container mutated within the caller's transaction
     * @param identifier      unique identifier for the statistic to remove
     * @param plugin          plugin namespace expected to own the statistic
     * @return {@code true} when at least one statistic entry was removed
     */
    public static boolean removeStatistic(
            final @NotNull RPlayerStatistic playerStatistic,
            final @NotNull String identifier,
            final @NotNull String plugin
    ) {
        // Prefer entity-level removal
        if (playerStatistic.removeStatistic(identifier, plugin)) {
            return true;
        }
        // Fallback: DB uniqueness is per identifier, ensure removal if plugin didn't match
        return removeByIdentifier(playerStatistic, identifier);
    }

    /**
     * Removes all statistics associated with a specific plugin namespace.
     *
     * @param playerStatistic statistic container mutated within the caller's transaction
     * @param plugin          plugin namespace whose statistics should be cleared
     * @return number of statistics deleted for the plugin
     */
    public static int removeStatisticsByPlugin(
            final @NotNull RPlayerStatistic playerStatistic,
            final @NotNull String plugin
    ) {
        final Set<String> idsForPlugin = playerStatistic.getStatistics().stream()
                .filter(stat -> stat.getPlugin().equals(plugin))
                .map(RAbstractStatistic::getIdentifier)
                .collect(Collectors.toSet());

        int removed = 0;
        for (final String id : idsForPlugin) {
            if (playerStatistic.removeStatistic(id, plugin)) {
                removed++;
            }
        }
        return removed;
    }

    /**
     * Retrieves a statistic value cast to the expected type when present.
     *
     * @param playerStatistic statistic container queried in the current transactional view
     * @param identifier      identifier of the statistic to look up
     * @param plugin          plugin namespace that owns the statistic
     * @param expectedType    desired return type for the statistic value
     * @param <T>             expected type token used for narrowing the return value
     * @return optional containing the statistic value cast to {@code T} when present and matching
     * the requested type; empty when absent or incompatible
     */
    @SuppressWarnings("unchecked")
    public static <T> Optional<T> getStatisticValue(
            final @NotNull RPlayerStatistic playerStatistic,
            final @NotNull String identifier,
            final @NotNull String plugin,
            final @NotNull Class<T> expectedType
    ) {
        return playerStatistic
                .getStatisticValue(identifier, plugin)
                .filter(expectedType::isInstance)
                .map(v -> (T) v);
    }

    /**
     * Retrieves a statistic value coerced to a {@link String} if present.
     *
     * @param playerStatistic statistic container queried in the current transactional view
     * @param identifier      identifier of the statistic to look up
     * @param plugin          plugin namespace that owns the statistic
     * @return string representation of the statistic value or {@code null} when unavailable
     */
    public static @Nullable String getStatisticAsString(
            final @NotNull RPlayerStatistic playerStatistic,
            final @NotNull String identifier,
            final @NotNull String plugin
    ) {
        return playerStatistic
                .getStatisticValue(identifier, plugin)
                .map(Object::toString)
                .orElse(null);
    }

    /**
     * Adds an increment to a numeric statistic and returns the resulting value.
     *
     * <p>If the statistic does not exist or is not numeric, no mutation occurs and {@code null} is
     * returned.</p>
     *
     * @param playerStatistic statistic container mutated within the caller's transaction
     * @param identifier      identifier of the numeric statistic to adjust
     * @param plugin          plugin namespace that owns the statistic
     * @param increment       delta applied to the stored numeric value
     * @return updated numeric value or {@code null} when the existing statistic is absent or not
     * numeric
     */
    public static @Nullable Double incrementNumericStatistic(
            final @NotNull RPlayerStatistic playerStatistic,
            final @NotNull String identifier,
            final @NotNull String plugin,
            final double increment
    ) {
        final Optional<Object> current = playerStatistic.getStatisticValue(identifier, plugin);
        if (current.isPresent() && current.get() instanceof Number num) {
            final double newValue = num.doubleValue() + increment;
            addOrUpdateStatistic(playerStatistic, identifier, plugin, newValue);
            return newValue;
        }
        return null;
    }

    /**
     * Sets a timestamp statistic to the current UTC time.
     *
     * <p>The timestamp is stored as a {@link LocalDateTime} to ensure Hibernate persists the field
     * using the date statistic mapping. The returned value reflects the epoch milliseconds written
     * so callers can use it immediately without re-fetching the statistic.</p>
     *
     * @param playerStatistic statistic container mutated within the caller's transaction
     * @param identifier      identifier of the timestamp statistic to update
     * @param plugin          plugin namespace that owns the statistic
     * @return epoch milliseconds representing the timestamp assigned to the statistic
     */
    public static long setCurrentTimestamp(
            final @NotNull RPlayerStatistic playerStatistic,
            final @NotNull String identifier,
            final @NotNull String plugin
    ) {
        final LocalDateTime now = LocalDateTime.now(ZoneOffset.UTC);
        addOrUpdateStatistic(playerStatistic, identifier, plugin, now);
        return now.toEpochSecond(ZoneOffset.UTC) * 1000L;
    }

    /**
     * Exports the statistic collection grouped by plugin.
     *
     * <p>The returned structure is a snapshot backed by new map instances, allowing callers to
     * serialize or inspect the values without mutating the underlying managed entities.</p>
     *
     * @param playerStatistic statistic container whose values are being exported
     * @return nested map keyed by plugin, then statistic identifier, containing the raw stored
     * values
     */
    public static @NotNull Map<String, Map<String, Object>> exportStatistics(
            final @NotNull RPlayerStatistic playerStatistic
    ) {
        final Map<String, Map<String, Object>> export = new HashMap<>();

        for (RAbstractStatistic statistic : playerStatistic.getStatistics()) {
            export
                    .computeIfAbsent(statistic.getPlugin(), k -> new HashMap<>())
                    .put(statistic.getIdentifier(), statistic.getValue());
        }

        return export;
    }

    /**
     * Imports statistics from an export payload.
     *
     * <p>Values are applied sequentially using
     * {@link #addStatisticsBulk(RPlayerStatistic, Map, String)} to preserve the same upsert
     * semantics and transactional guarantees as other insertion helpers.</p>
     *
     * @param playerStatistic statistic container mutated within the caller's transaction
     * @param importData      nested map keyed by plugin and statistic identifier containing values
     *                        to apply
     * @return number of statistics written or updated during the import
     */
    public static int importStatistics(
            final @NotNull RPlayerStatistic playerStatistic,
            final @NotNull Map<String, Map<String, Object>> importData
    ) {
        int importCount = 0;

        for (Map.Entry<String, Map<String, Object>> pluginEntry : importData.entrySet()) {
            final String plugin = pluginEntry.getKey();
            importCount += addStatisticsBulk(playerStatistic, pluginEntry.getValue(), plugin);
        }

        return importCount;
    }

    /**
     * Counts statistics grouped by plugin namespace.
     *
     * @param playerStatistic statistic container whose contents are analysed
     * @return map of plugin identifiers to counts of statistics managed for that plugin
     */
    public static @NotNull Map<String, Long> getStatisticCountByPlugin(
            final @NotNull RPlayerStatistic playerStatistic
    ) {
        return playerStatistic.getStatistics().stream()
                .collect(Collectors.groupingBy(
                        RAbstractStatistic::getPlugin,
                        Collectors.counting()
                ));
    }

    /**
     * Determines whether a statistic exists for a specific identifier and plugin pairing.
     *
     * @param playerStatistic statistic container queried in the current transactional view
     * @param identifier      identifier of the statistic to check
     * @param plugin          plugin namespace expected to own the statistic
     * @return {@code true} when a statistic is present for the given identifier and plugin
     */
    public static boolean hasStatistic(
            final @NotNull RPlayerStatistic playerStatistic,
            final @NotNull String identifier,
            final @NotNull String plugin
    ) {
        return playerStatistic.getStatisticValue(identifier, plugin).isPresent();
    }

    /**
     * Creates a concrete statistic entity based on the supplied value type.
     *
     * <p>Number values are normalised to {@code double}, while {@link LocalDateTime} values are
     * converted to epoch milliseconds so they can be stored as {@link RDateStatistic}. All
     * unsupported types fall back to {@link String} conversion to guarantee persistence.</p>
     *
     * @param identifier unique identifier for the statistic
     * @param plugin     plugin namespace that owns the statistic
     * @param value      value to store; supported types include {@link Boolean}, {@link Number},
     *                   {@link String}, {@link LocalDateTime}, and arbitrary objects convertible to
     *                   string
     * @return a statistic entity representing the provided value
     */
    private static @NotNull RAbstractStatistic createStatisticFromValue(
            final @NotNull String identifier,
            final @NotNull String plugin,
            final @NotNull Object value
    ) {
        if (value instanceof Boolean b) {
            return new RBooleanStatistic(identifier, plugin, b);
        }
        if (value instanceof Number number) {
            return new RNumberStatistic(identifier, plugin, number.doubleValue());
        }
        if (value instanceof String s) {
            return new RStringStatistic(identifier, plugin, s);
        }
        if (value instanceof LocalDateTime localDateTime) {
            final long timestamp = localDateTime.toEpochSecond(ZoneOffset.UTC) * 1000;
            return new RDateStatistic(identifier, plugin, timestamp);
        }
        // Fallback: store as string representation
        return new RStringStatistic(identifier, plugin, value.toString());
    }

    // ---- helpers ----

    /**
     * Locates a statistic entity by identifier without considering plugin namespaces.
     *
     * <p>Directly accesses the mutable internal statistic set to ensure Hibernate tracks any
     * in-place modifications to the returned entity.</p>
     *
     * @param playerStatistic statistic container whose internal collection is queried
     * @param identifier      unique identifier to search for
     * @return optional containing the managed statistic entity when present
     */
    private static Optional<RAbstractStatistic> findByIdentifier(
            final @NotNull RPlayerStatistic playerStatistic,
            final @NotNull String identifier
    ) {
        // CRITICAL: Use the internal mutable collection to ensure we get the actual Hibernate-managed entities
        // This is essential for in-place updates to be properly tracked by Hibernate
        final Set<RAbstractStatistic> stats = playerStatistic.getStatisticsInternal();
        return stats.stream()
                .filter(s -> s.getIdentifier().equals(identifier))
                .findFirst();
    }

    /**
     * Removes statistics by identifier across all plugin namespaces.
     *
     * @param playerStatistic statistic container mutated within the caller's transaction
     * @param identifier      unique identifier to remove
     * @return {@code true} when any statistics were removed
     */
    private static boolean removeByIdentifier(
            final @NotNull RPlayerStatistic playerStatistic,
            final @NotNull String identifier
    ) {
        // There is no direct API; simulate via known plugins present
        final Set<String> plugins = playerStatistic.getStatistics().stream()
                .filter(s -> s.getIdentifier().equals(identifier))
                .map(RAbstractStatistic::getPlugin)
                .collect(Collectors.toSet());

        boolean removedAny = false;
        for (final String plugin : plugins) {
            removedAny |= playerStatistic.removeStatistic(identifier, plugin);
        }
        return removedAny;
    }

    /**
     * Updates an existing statistic entity in place when the provided value is compatible with the
     * entity type.
     *
     * <p>The method leaves values unchanged when incompatible types are provided. Exceptions thrown
     * by the entity setters are swallowed and treated as type mismatches to keep the service API
     * side-effect free.</p>
     *
     * @param existing existing statistic entity managed by Hibernate
     * @param value    new value to apply to the statistic
     * @return {@code true} when the existing entity was updated without replacement
     */
    private static boolean updateExistingStatistic(
            final @NotNull RAbstractStatistic existing,
            final @NotNull Object value
    ) {
        try {
            if (existing instanceof RBooleanStatistic bStat) {
                if (value instanceof Boolean b) {
                    bStat.setValue(b);
                    return true;
                }
                return false;
            }
            if (existing instanceof RNumberStatistic nStat) {
                if (value instanceof Number n) {
                    nStat.setValue(n.doubleValue());
                    return true;
                }
                return false;
            }
            if (existing instanceof RStringStatistic sStat) {
                if (value instanceof String s) {
                    sStat.setValue(s);
                    return true;
                }
                // allow non-string overwrite by toString() to avoid churn
                sStat.setValue(value.toString());
                return true;
            }
            if (existing instanceof RDateStatistic dStat) {
                if (value instanceof LocalDateTime ldt) {
                    final long ts = ldt.toEpochSecond(ZoneOffset.UTC) * 1000L;
                    dStat.setValue(ts);
                    return true;
                }
                if (value instanceof Number n) {
                    dStat.setValue(n.longValue());
                    return true;
                }
                return false;
            }
        } catch (final Exception ignored) {
            return false;
        }
        return false;
    }
}