name: "RDQ"
version: ${version}
main: com.raindropcentral.rdq.RDQFree
loader: de.jexcellence.dependency.loader.PaperPluginLoader
api-version: ${apiVersion}
description: ${description}
author: RaindropCentral
website: https://raindropcentral.com
dependencies:
  server:
    Vault:
      load: BEFORE
      required: false
    LuckPerms:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
