name: "RDR"
version: ${version}
main: com.raindropcentral.rdr.RDRFree
api-version: '1.19'
description: ${description}
author: RaindropCentral
website: https://raindropcentral.com
softdepend:
  - Vault
  - JExEconomy
  - TheNewEconomy
