name: RCoreFree
main: com.raindropcentral.core.RCoreFree
loader: de.jexcellence.dependency.loader.PaperPluginLoader
version: 2.0.0
api-version: "1.19"
description: RCoreFree
authors: [ ItsRainingHP, JExcellence ]
website: https://www.raindropcentral.com
softdepend:
  - JECurrency
  - LuckPerms
  - Aura
  - ChestSort
  - CMI
  - DiscordSRV
  - EcoJobs
  - Essentials
  - EssentialsChat
  - EssentialsDiscord
  - EssentialsSpawn
  - HuskTowns
  - Jobs
  - mcMMO
  - Towny
  - TownyChat