package com.raindropcentral.commands;

import com.raindropcentral.commands.permission.PermissionHierarchyRegistrar;
import com.raindropcentral.commands.permission.PermissionParentProvider;
import com.raindropcentral.commands.utility.Command;
import de.jexcellence.configmapper.ConfigMapper;
import de.jexcellence.evaluable.CommandUpdater;
import de.jexcellence.evaluable.ConfigKeeper;
import de.jexcellence.evaluable.ConfigManager;
import de.jexcellence.evaluable.section.ACommandSection;
import org.bukkit.event.Listener;
import org.bukkit.plugin.java.JavaPlugin;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.lang.reflect.Constructor;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.CodeSource;
import java.util.List;
import java.util.jar.JarFile;
import java.util.logging.Level;
import java.util.stream.Stream;

/**
 * Generic CommandFactory that can register commands and listeners for any JavaPlugin.
 * Supports passing custom context objects (like RDQ, RDQFree, RDQPremium) to commands and listeners.
 *
 * <p>The factory drives the auto-registration pipeline outlined in {@code AGENTS.md}, injecting configuration sections so
 * commands inherit edition gating rules, localization hooks, and consistent constructor wiring across Paper and Spigot
 * distributions.
 *
 * @author JExcellence
 * @since 1.0.0
 * @version 1.0.1
 */
@SuppressWarnings("unchecked")
public class CommandFactory {
    private static final String CLASS_FILE_SUFFIX = ".class";
    private static final String COMMAND_PACKAGE = "command";
    private static final String COMMANDS_PACKAGE = "commands";

    /**
     * Root folder that stores command configuration files under the plugin's data directory.
     * Default value: {@code "commands"}. Dependency requirements: directory must exist within the plugin data path.
     * Thread safety: immutable constant safe for concurrent access.
     */
    private static final String COMMANDS_FOLDER = "commands";
    private static final String LISTENER_PACKAGE = "listener";
    private static final String LISTENERS_PACKAGE = "listeners";
    private static final String MODULE_INFO_CLASS = "module-info";
    private static final String PACKAGE_INFO_CLASS = "package-info";
    /**
     * Configuration key that contains permission metadata within each command section.
     * Default value: {@code "permissions"}. Dependency requirements: sections generated by the config mapper should
     * expose this key. Thread safety: immutable constant safe for concurrent use.
     */
    private static final String PERMISSIONS_SECTION = "permissions";

    /**
     * Plugin whose class loader is scanned for command and listener classes.
     * Default value: supplied during construction. Dependency requirements: must be the actively running Paper/Spigot
     * plugin. Thread safety: access should remain on the main thread because most Bukkit APIs are not thread-safe.
     */
    private final JavaPlugin loadedPlugin;
    /**
     * Optional context object forwarded to handlers requiring additional state (for example RDQ variants).
     * Default value: {@code null} when not provided. Dependency requirements: if supplied, commands/listeners must
     * declare constructors that accept it. Thread safety: treat as effectively immutable reference; avoid mutating the
     * object across threads without external synchronization.
     */
    private final Object contextObject; // Can be RDQ, RDQFree, RDQPremium, or any other context
    /**
     * Synchronizes Paper/Bukkit's command map with the generated command instances.
     * Default value: {@link CommandUpdater} instantiated per factory. Dependency requirements: relies on the
     * {@code de.jexcellence} evaluable library. Thread safety: not thread-safe; invoke on the main thread only.
     */
    private final CommandUpdater commandUpdater;

    /**
     * Constructor for CommandFactory without a context object (legacy support).
     * Behaviour: delegates to the full constructor with a {@code null} context so commands rely solely on the
     * {@link JavaPlugin} for dependencies. Failure modes: {@link NullPointerException} when {@code loadedPlugin} is
     * {@code null}. Asynchronous considerations: should be invoked during synchronous plugin bootstrap.
     *
     * @param loadedPlugin the JavaPlugin instance being bootstrapped
     */
    public CommandFactory(final @NotNull JavaPlugin loadedPlugin) {
        this(loadedPlugin, null);
    }

    /**
     * Constructor for CommandFactory with an optional context object.
     * The context object is forwarded to commands or listeners when their constructors declare it so.
     * Behaviour: initialises the {@link CommandUpdater} so edition-gated commands can be synchronized with Bukkit once
     * constructed. Failure modes: {@link NullPointerException} when {@code loadedPlugin} is {@code null}. Asynchronous
     * considerations: instantiate synchronously during plugin enablement to avoid thread-safety issues with Bukkit APIs.
     *
     * @param loadedPlugin  the JavaPlugin instance being bootstrapped
     * @param contextObject optional context object (e.g., RDQ instance) to pass to commands/listeners
     */
    public CommandFactory(
            final @NotNull JavaPlugin loadedPlugin,
            final @Nullable Object contextObject
    ) {
        this.loadedPlugin = loadedPlugin;
        this.contextObject = contextObject;
        this.commandUpdater = new CommandUpdater(this.loadedPlugin);
    }

    /**
     * Scans the plugin artifact for command and listener implementations annotated with.
     * {@link com.raindropcentral.commands.utility.Command} and registers them.
 *
 * <p>The discovery process performs two passes:
     * <ul>
     *     <li>Command classes under {@code *command*} packages are instantiated via {@link #registerCommand(Class)}.</li>
     *     <li>Listener classes under {@code *listener*} packages are instantiated via {@link #registerListener(Class)}.</li>
     * </ul>
     * Behavior: orchestrates edition-aware registration so free and premium variants receive the correct context.
     * Failure modes: any exception during discovery is logged and does not halt plugin enablement. Asynchronous
     * considerations: should be invoked on the Bukkit main thread during plugin startup because registration touches
     * non-thread-safe APIs.
     *
     * <p><b>OPTIMIZED:</b> Scans only the plugin's own classes instead of the full runtime class loader so Folia
     * startup does not stall on large dependency graphs.</p>
     */
    public void registerAllCommandsAndListeners() {
        try {
            final List<Class<?>> discoveredClasses = this.discoverRelevantClasses();

            discoveredClasses.stream()
                    .filter(this::isCommandClass)
                    .forEach(this::registerCommand);

            discoveredClasses.stream()
                    .filter(this::isListenerClass)
                    .forEach(this::registerListener);
        } catch (final Exception exception) {
            this.loadedPlugin.getLogger().log(
                    Level.WARNING,
                    "Could not register commands or listeners",
                    exception
            );
        }
    }

    private @NotNull List<Class<?>> discoverRelevantClasses() throws IOException, URISyntaxException {
        final Path codeSourcePath = this.resolveCodeSourcePath();
        final String pluginPackage = this.loadedPlugin.getClass().getPackageName();
        final List<String> classNames = Files.isDirectory(codeSourcePath)
                ? this.discoverClassNamesFromDirectory(codeSourcePath, pluginPackage)
                : this.discoverClassNamesFromJar(codeSourcePath, pluginPackage);

        return classNames.stream()
                .<Class<?>>mapMulti((className, downstream) -> {
                    final Class<?> loadedClass = this.tryLoadClass(className);
                    if (loadedClass != null) {
                        downstream.accept(loadedClass);
                    }
                })
                .toList();
    }

    private @NotNull Path resolveCodeSourcePath() throws URISyntaxException, IOException {
        final CodeSource codeSource = this.loadedPlugin.getClass().getProtectionDomain().getCodeSource();
        if (codeSource == null || codeSource.getLocation() == null) {
            throw new IOException("Could not resolve the plugin code source for command discovery.");
        }
        return Path.of(codeSource.getLocation().toURI());
    }

    private @NotNull List<String> discoverClassNamesFromDirectory(
            final @NotNull Path codeSourcePath,
            final @NotNull String pluginPackage
    ) throws IOException {
        try (Stream<Path> paths = Files.walk(codeSourcePath)) {
            return paths
                    .filter(Files::isRegularFile)
                    .map(codeSourcePath::relativize)
                    .map(Path::toString)
                    .map(this::toClassName)
                    .filter(className -> this.isRelevantClassName(className, pluginPackage))
                    .sorted()
                    .toList();
        }
    }

    private @NotNull List<String> discoverClassNamesFromJar(
            final @NotNull Path codeSourcePath,
            final @NotNull String pluginPackage
    ) throws IOException {
        try (JarFile jarFile = new JarFile(codeSourcePath.toFile())) {
            return jarFile.stream()
                    .filter(entry -> !entry.isDirectory())
                    .map(entry -> this.toClassName(entry.getName()))
                    .filter(className -> this.isRelevantClassName(className, pluginPackage))
                    .sorted()
                    .toList();
        }
    }

    private @Nullable Class<?> tryLoadClass(final @NotNull String className) {
        try {
            return Class.forName(className, false, this.loadedPlugin.getClass().getClassLoader());
        } catch (final ClassNotFoundException | LinkageError ignored) {
            return null;
        }
    }

    private boolean isRelevantClassName(final @NotNull String className, final @NotNull String pluginPackage) {
        if (className.isBlank()
                || !className.startsWith(pluginPackage + ".")
                || className.contains("$")
                || className.endsWith("." + PACKAGE_INFO_CLASS)
                || className.endsWith("." + MODULE_INFO_CLASS)) {
            return false;
        }

        final int packageSeparatorIndex = className.lastIndexOf('.');
        if (packageSeparatorIndex <= 0) {
            return false;
        }

        final String packageName = className.substring(0, packageSeparatorIndex);
        return this.isCommandPackage(packageName) || this.isListenerPackage(packageName);
    }

    private boolean isCommandClass(final @NotNull Class<?> clazz) {
        return clazz.isAnnotationPresent(Command.class) && this.isCommandPackage(clazz.getPackageName());
    }

    private boolean isListenerClass(final @NotNull Class<?> clazz) {
        return Listener.class.isAssignableFrom(clazz) && this.isListenerPackage(clazz.getPackageName());
    }

    private boolean isCommandPackage(final @NotNull String packageName) {
        return this.hasPackageSegment(packageName, COMMAND_PACKAGE)
                || this.hasPackageSegment(packageName, COMMANDS_PACKAGE);
    }

    private boolean isListenerPackage(final @NotNull String packageName) {
        return this.hasPackageSegment(packageName, LISTENER_PACKAGE)
                || this.hasPackageSegment(packageName, LISTENERS_PACKAGE);
    }

    private boolean hasPackageSegment(final @NotNull String packageName, final @NotNull String segment) {
        for (final String packageSegment : packageName.split("\\.")) {
            if (segment.equals(packageSegment)) {
                return true;
            }
        }
        return false;
    }

    private @NotNull String toClassName(final @NotNull String resourceName) {
        final String normalizedResourceName = resourceName.replace('\\', '/');
        if (!normalizedResourceName.endsWith(CLASS_FILE_SUFFIX)) {
            return "";
        }

        return normalizedResourceName
                .substring(0, normalizedResourceName.length() - CLASS_FILE_SUFFIX.length())
                .replace('/', '.');
    }

    /**
     * Instantiates a command class by locating its configuration section, selecting the most specific.
     * constructor, and delegating to the {@link CommandUpdater} for registration.
 *
 * <p>Constructor selection follows these precedence rules:
     * <ol>
     *     <li>Exact match with the configured context object's class.</li>
     *     <li>Constructor whose parameter type is assignable from the context object's class.</li>
     *     <li>Constructor accepting the concrete {@link JavaPlugin} implementation.</li>
     *     <li>Constructor whose second parameter matches any superclass of the plugin (checked via
     *     {@link #isAssignableFromSuperclass(Class, Class)}).</li>
     * </ol>
     * Behaviour: ensures commands receive localized sections and the appropriate edition context before being
     * synchronized with Bukkit. Failure modes: logs warnings when constructors cannot be matched or instantiation fails
     * but continues processing remaining commands. Asynchronous considerations: must be executed on the main thread to
     * respect Bukkit&apos;s thread-safety requirements.
     *
     * @param commandClass discovered command implementation annotated with {@link Command}
     */
    private void registerCommand(Class<?> commandClass) {
        try {
            String className = commandClass.getSimpleName();
            char prefix = className.charAt(0);
            String sectionClassName = prefix + className.substring(1) + "Section";
            String configFileName = prefix + className.substring(1) + ".yml";
            String packageName = commandClass.getPackageName();

            Class<? extends ACommandSection> sectionClass = (Class<? extends ACommandSection>) Class.forName(packageName + "." + sectionClassName);

            final ACommandSection mapSection = getACommandSection(configFileName, sectionClass, className);

            if (mapSection instanceof PermissionParentProvider permissionParentProvider) {
                try {
                    PermissionHierarchyRegistrar.register(
                        this.loadedPlugin,
                        mapSection.getPermissions(),
                        permissionParentProvider.getPermissionParents()
                    );
                } catch (final Exception exception) {
                    this.loadedPlugin.getLogger().log(
                        Level.WARNING,
                        "Could not register permission hierarchy for command: " + commandClass.getName(),
                        exception
                    );
                }
            }

            BukkitCommand command = null;

            try {
                Constructor<?> selectedConstructor = null;
                Object secondArg = null;

                // Try to find a compatible constructor
                for (final Constructor<?> ctor : commandClass.getDeclaredConstructors()) {
                    Class<?>[] paramTypes = ctor.getParameterTypes();

                    // Must have 2 parameters, first must be the section
                    if (paramTypes.length != 2 || !paramTypes[0].isAssignableFrom(mapSection.getClass())) {
                        continue;
                    }

                    Class<?> secondParamType = paramTypes[1];

                    // Priority 1: Exact match with context object's class
                    if (contextObject != null && secondParamType.equals(contextObject.getClass())) {
                        selectedConstructor = ctor;
                        secondArg = contextObject;
                        break;
                    }

                    // Priority 2: Context object is assignable to parameter type (polymorphism)
                    // e.g., RDQFree/RDQPremium can be passed to Constructor(Section, RDQ)
                    if (contextObject != null && secondParamType.isAssignableFrom(contextObject.getClass())) {
                        selectedConstructor = ctor;
                        secondArg = contextObject;
                        break;
                    }

                    // Priority 3: JavaPlugin constructor (direct match)
                    if (secondParamType.isAssignableFrom(this.loadedPlugin.getClass())) {
                        selectedConstructor = ctor;
                        secondArg = this.loadedPlugin;
                        // Don't break - keep looking for better match
                        continue;
                    }

                    // Priority 4: Check superclass hierarchy safely
                    if (isAssignableFromSuperclass(secondParamType, this.loadedPlugin.getClass())) {
                        selectedConstructor = ctor;
                        secondArg = this.loadedPlugin;
                        // Don't break - keep looking for better match
                    }
                }

                if (selectedConstructor != null) {
                    command = (BukkitCommand) selectedConstructor.newInstance(mapSection, secondArg);
                } else {
                    this.loadedPlugin.getLogger().log(
                            Level.WARNING,
                            "No compatible constructor found for command: " + commandClass.getName()
                                    + " (requires constructor with ACommandSection and JavaPlugin or context object)"
                    );
                    return;
                }
            } catch (final Exception exception) {
                this.loadedPlugin.getLogger().log(
                        Level.WARNING,
                        "Could not register command '" + commandClass.getName() + "'",
                        exception
                );
                return;
            }

            if (className.equalsIgnoreCase("pr18n")) {
                command.setName(this.loadedPlugin.getName().toLowerCase() + ":pr18n");
                command.getAliases().add(this.loadedPlugin.getName().toLowerCase() + "reloadI18n");
            }

            this.commandUpdater.tryRegisterCommand(command);
            this.commandUpdater.trySyncCommands();

        } catch (final Exception exception) {
            this.loadedPlugin.getLogger().log(
                    Level.WARNING,
                    "Could not register command: " + commandClass.getName(),
                    exception
            );
        }
    }

    /**
     * Loads a command configuration section, ensuring the YAML file and section type follow the.
     * naming conventions documented in {@code AGENTS.md}.
     * Behaviour: hydrates the section so localization hooks and edition gating toggles are available to the command
     * constructor. Failure modes: throws {@link Exception} when mapping fails; callers log and continue processing.
     * Asynchronous considerations: should run on the main thread or during synchronous startup because configuration
     * I/O is tied to the plugin data folder.
     *
     * @param configFileName expected YAML file name (e.g. {@code Example.yml})
     * @param sectionClass   configuration section type corresponding to the command
     * @param className      command simple name used to compute the configuration path
     * @return hydrated command section instance ready for use in the command constructor
     * @throws Exception when the configuration cannot be loaded or mapped to the section class
     */
    private ACommandSection getACommandSection(String configFileName, Class<? extends ACommandSection> sectionClass, String className) throws Exception {
        final ConfigManager cfgManager = new ConfigManager(
                this.loadedPlugin,
                COMMANDS_FOLDER
        );
        final ConfigMapper cfgMapper = cfgManager.loadConfig(configFileName.toLowerCase());
        final ConfigKeeper<? extends ACommandSection> cfgKeeper = new ConfigKeeper<>(
                cfgManager,
                configFileName.toLowerCase(),
                sectionClass
        );
        return cfgKeeper.mapSection(
                COMMANDS_FOLDER + "." + className.toLowerCase()
        );
    }

    /**
     * Safely checks whether {@code targetType} is assignable from any superclass of {@code sourceClass}.
     * The helper is used when evaluating constructor compatibility against the plugin type while
     * guarding against {@code null} superclasses.
     * Behaviour: iterates the superclass hierarchy without triggering {@link NullPointerException}. Failure modes: none;
     * returns {@code false} when no match is found. Asynchronous considerations: pure computation safe on any thread.
     *
     * @param targetType  type being matched (typically the constructor parameter)
     * @param sourceClass class whose hierarchy should be inspected
     * @return {@code true} when the target type matches any superclass, otherwise {@code false}
     */
    private boolean isAssignableFromSuperclass(Class<?> targetType, Class<?> sourceClass) {
        Class<?> current = sourceClass.getSuperclass();
        while (current != null) {
            if (targetType.isAssignableFrom(current)) {
                return true;
            }
            current = current.getSuperclass();
        }
        return false;
    }

    /**
     * Instantiates a listener class and registers it with Bukkit's {@link org.bukkit.plugin.PluginManager}.
     * Constructor precedence mirrors command registration but for single-argument constructors:
     * <ol>
     *     <li>Exact match with the context object's class.</li>
     *     <li>Constructor whose parameter type is assignable from the context object's class.</li>
     *     <li>Constructor receiving the concrete {@link JavaPlugin} implementation.</li>
     * </ol>
     * Behaviour: ensures listeners receive the same edition-aware context as commands. Failure modes: logs warnings
     * when no compatible constructor exists or instantiation fails. Asynchronous considerations: must execute on the main
     * thread because listener registration interacts with Bukkit&apos;s event system.
     *
     * @param listenerClass discovered listener implementation under a {@code *listener*} package
     */
    private void registerListener(final @NotNull Class<?> listenerClass) {
        try {
            if (!Listener.class.isAssignableFrom(listenerClass)) {
                return;
            }

            Listener listener = null;
            Constructor<?> selectedConstructor = null;
            Object constructorArg = null;

            // Try to find a compatible constructor
            for (final Constructor<?> ctor : listenerClass.getDeclaredConstructors()) {
                Class<?>[] paramTypes = ctor.getParameterTypes();

                // Skip if not single-parameter constructor
                if (paramTypes.length != 1) {
                    continue;
                }

                Class<?> paramType = paramTypes[0];

                // Priority 1: Exact match with context object's class
                if (contextObject != null && paramType.equals(contextObject.getClass())) {
                    selectedConstructor = ctor;
                    constructorArg = contextObject;
                    break;
                }

                // Priority 2: Context object is assignable to parameter type (polymorphism)
                // e.g., RDQFree/RDQPremium can be passed to Constructor(RDQ)
                if (contextObject != null && paramType.isAssignableFrom(contextObject.getClass())) {
                    selectedConstructor = ctor;
                    constructorArg = contextObject;
                    break;
                }

                // Priority 3: JavaPlugin constructor (legacy)
                if (paramType.isAssignableFrom(this.loadedPlugin.getClass())) {
                    selectedConstructor = ctor;
                    constructorArg = this.loadedPlugin;
                    // Don't break - keep looking for better match
                }
            }

            if (selectedConstructor != null) {
                listener = (Listener) selectedConstructor.newInstance(constructorArg);
                this.loadedPlugin.getServer().getPluginManager().registerEvents(
                        listener,
                        this.loadedPlugin
                );
            } else {
                this.loadedPlugin.getLogger().log(
                        Level.WARNING,
                        "No compatible constructor found for listener: " + listenerClass.getName()
                                + " (requires JavaPlugin or context object)"
                );
            }

        } catch (final Exception exception) {
            this.loadedPlugin.getLogger().log(
                    Level.WARNING,
                    "Could not register listener: " + listenerClass.getName(),
                    exception
            );
        }
    }

    /**
     * Returns the plugin instance being scanned by the factory.
     * Behaviour: exposes the plugin reference for downstream consumers that may need to schedule tasks or query
     * configuration. Failure modes: none. Asynchronous considerations: callers should still respect Bukkit&apos;s
     * main-thread rules when using the returned plugin.
     *
     * @return plugin provided during construction
     */
    @NotNull
    public JavaPlugin getLoadedPlugin() {
        return this.loadedPlugin;
    }

    /**
     * Returns the optional context object forwarded to commands and listeners.
     * Behaviour: allows callers to differentiate edition-specific wiring (for example, premium context vs free).
     * Failure modes: none. Asynchronous considerations: treat the returned instance as effectively immutable unless the
     * owning plugin coordinates thread-safe access.
     *
     * @return configured context object or {@code null} when none was supplied
     */
    @Nullable
    public Object getContextObject() {
        return this.contextObject;
    }
}
